services:
  - docker

script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker build -t dpca/iracket-docker .;
    docker push dpca/iracket-docker;
    fi
